version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  run_model:
    run: python:latest analysis/pymodel.py
    needs: [ generate_study_population ]
    outputs:
      moderately_sensitive:
        log: logs/pymodel_log.txt
        figure1: output/plots/corr_heatmap.png
